apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook-sample
    app.kubernetes.io/part-of: operator-playground
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-playground
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
  size: 1
  configMapName: cm
